### ISSUE TITLE
How is EWR measured 

### ISSUE THREAD

**Issue by 1a1a11a** [NVSL/OptaneStudy#6]
Hi authors, 
    I tried to find this in the repo, but I haven't found it, do you mind telling me how is effective write ratio measured? Thank you!

**Comment by pocean** [comment]
In this paper, authors said that "LATTester collects a large set of hardware counters at both the CPU and NVDIMM.", and I found that cacheprobe and imcprobe may be used for ewr but I'm not sure. Besides, I don't know how to collect the hardware counters at NVDIMM.

**Comment by 1a1a11a** [comment]
Thank you! I did not notice this.

**Comment by pocean** [comment]
> Thank you! I did not notice this.

Do you try to check the hardware counters using ipmctl? Does it work?

**Comment by 1a1a11a** [comment]
Yes, but I haven't ran anything yet, so I am not sure my interpretation of the counters are correct, will get back here when I do this.

**Comment by wwyf** [comment]
I have the same question. Maybe someone can provide the guideline for measuring EWR ?

**Comment by sheepx86** [comment]
Hi @1a1a11a , I am a co-author of the paper. When running the benchmark, we actually collected four metrics:

***A***. The number of bytes written at the application level (simple math since we were running short assembly snippets).
***B***. The PMU counters for memory controller (and LLC) related events (we used the `sepdk` driver, which may require vTune license), the documentation can be found [here(1)](https://software.intel.com/content/www/us/en/develop/blogs/documentation-for-uncore-performance-monitoring-units.html). I believe you can use [opcm(2)](https://github.com/opcm/pcm) or [pmu-tools(3)](https://github.com/andikleen/pmu-tools) to achieve something similar.
***C***. The counters reported by AEPWatch (*we did not report AEPWatch data in the paper as it might be Intel proprietary).
***D***. The Optane PMM counter queried using `ipmctl`, the documentation can be found [here(4)](https://docs.pmem.io/ipmctl-user-guide/instrumentation/show-device-performance).

The EWR numbers reported in the paper were calculated based on ***B*** and ***D***. If there is no significant caching (e.g. using `ntstore` or having certain memory access patterns), ***A*** and ***B*** should be very close.

For our experiments, AEPWatch(***C***) and ipmctl(***D***) showed similar results (I believe they are from the same source), with AEPWatch being more accurate/flexible. A recent [paper(5)](https://doi.org/10.1109/LCA.2020.2987303) mentioned that AEPWatch is an open-sourced tool (https://github.com/intel/memory-optimizer). If that is the case, I would recommend you to use ***B*** and ***C*** to calculate EWR.

Hope this helps!

#### Reference:
1. https://software.intel.com/content/www/us/en/develop/blogs/documentation-for-uncore-performance-monitoring-units.html
2. https://github.com/opcm/pcm
3. https://github.com/andikleen/pmu-tools
4. https://docs.pmem.io/ipmctl-user-guide/instrumentation/show-device-performance
5. T. Mason, T. D. Doudali, M. Seltzer and A. Gavrilovska, "Unexpected Performance of Intel® Optane™ DC Persistent Memory," in IEEE Computer Architecture Letters, vol. 19, no. 1, pp. 55-58, 1 Jan.-June 2020, [doi: 10.1109/LCA.2020.2987303](https://doi.org/10.1109/LCA.2020.2987303).

**Comment by sheepx86** [comment]
@pocean We also observed the background writes (we are not certain what those writes are either, maybe AIT writebacks). When running actual benchmarks, the delta of the counter will be several magnitudes higher than the increase when idle, making them effectively noise.

**Comment by wwyf** [comment]
This is helpful, thank you !!

**Comment by wwyf** [comment]
This is very helpful, thanks! ! !

**Comment by 1a1a11a** [comment]
This is very helpful. Thank you!
